name: CML & DVC
on: [push]
permissions:
  contents: write
  pull-requests: write
jobs:
  train-and-report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip' # caching pip dependencies
      - uses: iterative/setup-dvc@v1
      - name: Train model
        #env:
          #GDRIVE_CREDENTIALS_DATA: ${{ secrets.GDRIVE_CREDENTIALS_DATA }}
        run: |
          echo "Starting"
          pip install -r requirements.txt  # Install dependencies
          git config --global user.email "dinho1994@gmail.com"
          git config --global user.name "AndersonSheep"
          git clone https://github.com/AndersonSheep/MLOPS2.git
          cd MLOPS2
          dvc pull --verbose
          dvc exp run # repro                        # Reproduce pipeline  para treinar do 0: dvc exp run
